import '../models/skill.dart';
import '../models/routine.dart';

class SampleDataService {
  /// パフォーマンス系のサンプル技データ一覧
  static List<Skill> getSampleSkills() {
    final now = DateTime.now();
    return [
      Skill(
        id: 'sample_001',
        title: 'バックフリップ',
        category: 'アクロバット',
        tags: ['アクロ', '空中技', '基礎'],
        difficulty: 4,
        mastery: 85,
        successCount: 42,
        failCount: 8,
        notes: '踏み切りのタイミングが重要。膝を素早く引き付けること。',
        tips: '目線を固定して、最後まで回り切ることを意識する。着地は膝を軽く曲げて衝撃を吸収。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 30)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
      Skill(
        id: 'sample_002',
        title: 'トスジャグリング（3ボール）',
        category: 'ジャグリング',
        tags: ['ジャグリング', '基礎', '3ボール'],
        difficulty: 2,
        mastery: 95,
        successCount: 120,
        failCount: 5,
        notes: '基本のカスケードパターン。',
        tips: 'ボールを高く投げすぎず、一定の高さを保つ。視線は中央上部に固定。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1533561052604-c3bebb2a0000?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 60)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Skill(
        id: 'sample_003',
        title: 'フレアチップトリック',
        category: 'フレア',
        tags: ['フレア', 'ボトル', '上級'],
        difficulty: 5,
        mastery: 45,
        successCount: 15,
        failCount: 30,
        notes: 'ボトルのグリップが安定しないと失敗しやすい。',
        tips: '手首のスナップを意識。練習はプラスチックボトルで行うと安全。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 14)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Skill(
        id: 'sample_004',
        title: 'ムーンウォーク',
        category: 'ダンス',
        tags: ['ダンス', 'ステップ', 'MJ'],
        difficulty: 3,
        mastery: 70,
        successCount: 55,
        failCount: 10,
        notes: 'フロアとの摩擦が重要。靴底が滑らかなものを使用。',
        tips: '体重移動をゆっくり練習。かかとを上げたまま前足をスライドさせる感覚を覚える。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1547153760-18fc86324498?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 45)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Skill(
        id: 'sample_005',
        title: 'コインマジック（消える）',
        category: 'マジック',
        tags: ['マジック', 'コイン', '手品'],
        difficulty: 3,
        mastery: 60,
        successCount: 30,
        failCount: 20,
        notes: 'パームの角度が肝。観客の視線誘導が必要。',
        tips: 'フィンガーパームを完璧にしてから次のステップへ。ミスディレクションを練習する。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507878866276-a947ef722fee?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 20)),
        updatedAt: now.subtract(const Duration(days: 7)),
      ),
      Skill(
        id: 'sample_006',
        title: 'ヘッドスピン',
        category: 'ブレイクダンス',
        tags: ['ブレイクダンス', 'パワームーブ', '頭'],
        difficulty: 5,
        mastery: 20,
        successCount: 5,
        failCount: 25,
        notes: '頭の保護が最重要。マット使用必須。',
        tips: '最初は膝をついた状態から練習。首周りの筋トレも欠かさず行う。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 7)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Skill(
        id: 'sample_007',
        title: 'カードシャッフル（リフルシャッフル）',
        category: 'マジック',
        tags: ['マジック', 'カード', '基礎'],
        difficulty: 2,
        mastery: 90,
        successCount: 200,
        failCount: 10,
        notes: 'カードの角を正確に合わせること。',
        tips: '親指の圧力を一定に保ち、ゆっくりリリースする。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 90)),
        updatedAt: now.subtract(const Duration(days: 4)),
      ),
      Skill(
        id: 'sample_008',
        title: 'ファイヤーポイ',
        category: 'フレア',
        tags: ['ファイヤー', 'ポイ', '上級'],
        difficulty: 4,
        mastery: 55,
        successCount: 20,
        failCount: 8,
        notes: '安全装備必須。消火器を常備すること。',
        tips: '最初は素手（チェーンなし）で動きを完璧にしてから火をつける。',
        thumbnailUrl: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=400&h=225&fit=crop',
        createdAt: now.subtract(const Duration(days: 25)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
    ];
  }

  /// サンプルルーティンデータ
  static List<Routine> getSampleRoutines() {
    final now = DateTime.now();
    return [
      Routine(
        id: 'routine_001',
        title: 'ステージオープニング',
        skillIds: ['sample_004', 'sample_001', 'sample_002'],
        notes: '5分間のオープニングルーティン。ダンスから入ってアクロバットで盛り上げる。',
        createdAt: now.subtract(const Duration(days: 10)),
      ),
      Routine(
        id: 'routine_002',
        title: 'マジックショー構成',
        skillIds: ['sample_007', 'sample_005'],
        notes: 'クロースアップマジックのルーティン。15分想定。',
        createdAt: now.subtract(const Duration(days: 5)),
      ),
    ];
  }
}
